### ISSUE TITLE
Adding new languages and support

### ISSUE THREAD

**Issue by leandrodamascena** [SnapPetal/cdk-simplewebsite-deploy#26]
Just opening this ticket to remember to add Python/Java/C# support to this project.
Also, I'm not sure if the name "cdk-cloudfront-deploy" is appropriate to this stack, I think you may change it to "cdk-simplewebsite-deploy" or another name, but it's just a through!

I'n a very CDK enthusiast and I can help you.

**Comment by SnapPetal** [comment]
I like the name you suggested.  New to this but I guess we can see what breaks.

**Comment by SnapPetal** [comment]
@leandrodamascena Do you know what is needed in projen to support the other languages?

**Comment by leandrodamascena** [comment]
Hmm lets go:
1 - Python - Go to https://pypi.org/ and create an account and keys
2 - .NET - Go to https://pypi.org/project/twine/ and follow the documentation
3 - Java - This is a little bit complex because Sonartype requires domain to namespace, then java version can wait.

After you must add to ".projenrc.js" file the target.

1 - Python 
```
  python: {
    distName: 'cdk-simplewebsite-deploy',
    module: 'cdk_simplewebsite_deploy',
  },
```

2 - .NET

```
  dotnet: {
    dotNetNamespace: 'company.simplewebsite',
    packageId: 'Company.Simplewebsite'
  },
```

Now you must go to GitHub setting and new secrets:

.NET - 
KEY NAME = NUGET_API_KEY
KEY VALUE = THE KEY

PYTHON
KEY NAMES = TWINE_USERNAME AND TWINE_PASSWORD
KEY VALUES = THE VALUES

Projen will create the Github action and will publish atomically

**Comment by SnapPetal** [comment]
@leandrodamascena Does this make sense for the .NET package.

  dotnet: {
    dotNetNamespace: 'thonbecker.simplewebsite',
    packageId: 'ThonBecker.SimpleWebsitePackage',
  },

**Comment by SnapPetal** [comment]
Still need to add Java package.

**Comment by leandrodamascena** [comment]
Follow this steps to create sonatype namespace https://dzone.com/articles/publish-your-artifacts-to-maven-central.

After that add this to ".projenrc.js"
```

java: {
     javaPackage: 'com.company.simplewebsitedeploy',
     mavenGroupId: 'com.company',
     mavenArtifactId: 'cdk-simplewebsite-deploy'
   },
```

**Comment by leandrodamascena** [comment]
Opz, I forgot

You must add new secrets

MAVEN_GPG_PRIVATE_KEY
MAVEN_GPG_PRIVATE_KEY_PASSPHRASE
MAVEN_PASSWORD
MAVEN_USERNAME
MAVEN_STAGING_PROFILE_ID
